# Commands to run Regression Tests
#------------------------------------
# default fallback config test : mvn exec:java -Denv=config
# ERP Regression  test : mvn exec:java -Denv=erp
# WE1 Super Admin Side Regression  test : mvn exec:java -Denv=we1_superadmin


# Application URL
base.url=https://www.google.com
# Browser Settings
browser=chrome
headless=false

# Wait Timeouts
implicit.wait=10
explicit.wait=30

filter.name=TC_CA_
#excel.name=Book1.csv
#excel.name=Book1.csv
excel.name=config_regression.xlsx
#excel.name=run_sequential.csv
sheets.name=checkConfig