# Login Credentials
admin.email=administrator
admin.password=eit@123

# Application URL
base.url=https://erp.qa.ethicalintelligent.com/
dashboard.url=https://erp.qa.ethicalintelligent.com/
# Browser Settings
browser=chrome
headless=false

# Wait Timeouts
implicit.wait=10
explicit.wait=30

filter.name=TC_CA_
#excel.name=Book1.csv
#excel.name=Book1.csv
excel.name=erp_regression.xlsx
#excel.name=run_sequential.csv
sheets.name=erpLogin