# Login Credentials
admin.email=super_admin@gmail.com
admin.password=R1mep@321

# Application URL
base.url=https://dev.we1.co/#/login
dashboard.url=https://dev.we1.co/#/page-module/dashboard_dynamic
# Browser Settings
browser=chrome
headless=false

# Database Configuration
db.url=jdbc:postgresql://194.233.75.197:5432/we1
db.user=postgres
db.password=we12025

# Wait Timeouts
implicit.wait=10
explicit.wait=30

filter.name=TC_CA_
excel.name=we1_superAdmin_regression.xlsx
#Test to run for super admin side add sheet name from this list below to sheets.name to run that sheet:
# SuperAdminLogin,AddCustomer,AddCityArea,AddCityAdmin,AddAutoDriver,AddBikeDriver,AddTaxiDriver,
# TransportServiceCompleteTest,AddStore,StoreOperations,StoreStatusManagement,DeliveryServiceCompleteTest,
# AddProvider,ProviderServiceCompleteTest,SubscriptionPlanTest,AddTransportCityAdmin,DataCleanUpSheet
sheets.name=SuperAdminLogin,AddCustomer,AddCityArea,AddCityAdmin,AddAutoDriver,AddBikeDriver,AddTaxiDriver,TransportServiceCompleteTest,AddStore,StoreOperations,StoreStatusManagement,DeliveryServiceCompleteTest,AddProvider,ProviderServiceCompleteTest,SubscriptionPlanTest,AddTransportCityAdmin,DataCleanUpSheet