# ==========================================
# WEB LOGIN CREDENTIALS
# ==========================================
admin.email=super_admin@gmail.com
admin.password=R1mep@321

# ==========================================
# APPLICATION URLS
# ==========================================
base.url=https://dev.we1.co/#/login
dashboard.url=https://dev.we1.co/#/page-module/dashboard_dynamic

# ==========================================
# BROWSER SETTINGS
# ==========================================
browser=chrome
headless=false

# ==========================================
# MOBILE INFRASTRUCTURE
# ==========================================
# Appium Server URL
appium.url=http://127.0.0.1:4723

# Emulator Device IDs (from adb devices)
user.device.id=emulator-5554
driver.device.id=emulator-5556

# Local APK Paths (Outside project to avoid Git errors)
user.apk.path=C:/EIT_PROJECTS/WE1_MOBILE_APPS/We1_User.apk
driver.apk.path=C:/EIT_PROJECTS/WE1_MOBILE_APPS/We1_Driver.apk

# App Packages & Activities
# Verified App Details
user.app.package=com.we1.customer
user.app.activity=com.we1.customer.MainActivity

driver.app.package=com.we1.driver
driver.app.activity=com.we1.driver.MainActivity

# ==========================================
# DATABASE CONFIGURATION
# ==========================================
db.url=jdbc:postgresql://194.233.75.197:5432/we1
db.user=postgres
db.password=we12025

# ==========================================
# TIMEOUTS & EXECUTION SETTINGS
# ==========================================
implicit.wait=10
explicit.wait=60

filter.name=TC_CA_
excel.name=we1_hybrid_regression.xlsx
#Test to run for hybrid testing add sheet name from this list below to sheets.name to run that sheet:
# SuperAdminLogin,Rebooter,AddAutoDriver,AutoRideLifecycleTest,AddCustomer,ApprovedAutoDriver,SubscriptionPlanCheck
# TransportServiceCompleteTest,AddStore,StoreOperations,StoreStatusManagement,DeliveryServiceCompleteTest,
# AddProvider,ProviderServiceCompleteTest,SubscriptionPlanTest,AddTransportCityAdmin,DataCleanUpSheet
#RebooterAccess,SubscriptionPlanAccess,AutoRideAccessTest

# Test Sheets to execute
sheets.name=SubscriptionPlanAccess