# =========================================================================
# MOBILE CUSTOMER/USER APP LOCATORS REPOSITORY
# =========================================================================

# Welcome & System Authorization Onboarding Elements
mobile.customer.get_started.btn=accessibility=Get Started
mobile.customer.permission_allow.btn=id=com.android.permissioncontroller:id/permission_allow_button
mobile.customer.next.btn=accessibility=Next
mobile.customer.back.btn=accessibility=Back

# Authentication Profiles Fields Input Layouts
mobile.customer.ride_complete.+91=accessibility=+91
mobile.customer.mobile_number_field.btn=accessibility=Mobile Number
mobile.customer.cancel.btn=accessibility=Cancel
mobile.customer.edit_text.input=automator=new UiSelector().className("android.widget.EditText").instance(1)
mobile.customer.continue.btn=accessibility=Continue
mobile.customer.finish.btn=accessibility=Finish
mobile.customer.location_allow.btn=id=com.android.permissioncontroller:id/permission_allow_foreground_only_button

# Booking Selection & Dynamic Maps Coordinates Intersections
mobile.customer.home_page.home_icon=automator=new UiSelector().resourceId("Home")
mobile.customer.home_page.profile_icon=automator=new UiSelector().resourceId("Profile")
mobile.customer.home_page.rides_icon=automator=new UiSelector().resourceId("Rides")

#Edit Profile Section
mobile.customer.profile_Details.edit_profile_icon=automator=new UiSelector().resourceId("profile_pencil_icon")


# Booking Selection & Dynamic Maps Coordinates Intersections
mobile.customer.auto_ride.btn=accessibility=Auto Ride
mobile.customer.destination.input=automator=new UiSelector().resourceId("drop_location_textfield")
mobile.customer.set_location_map.btn=accessibility=Set location on the map
mobile.customer.destination_suggestion_first=automator=new UiSelector().className("android.widget.FrameLayout").instance(0)
mobile.customer.destination_entrance_location=accessibility=Anjappar Chettinad Restaurant
mobile.customer.confirm.btn=accessibility=Confirm
mobile.customer.ride_now.btn=accessibility=Ride Now

# =========================================================================
# MOBILE CUSTOMER/USER APP - PAYMENT & REVIEW lifecycle LOCATORS
# =========================================================================

# Post-Ride Checkout Controls
mobile.customer.proceed_to_pay.btn=accessibility=Proceed To Pay

# Feedback and Rating Screens
mobile.customer.give_review.btn=accessibility=Give Review
mobile.customer.submit_rating.btn=accessibility=Submit

# Trip Closure Flows
mobile.customer.done.btn=accessibility=Done

#Customer Subscription Side
mobile.customer.subscription.btn=accessibility=Subscription
mobile.customer.dynamic_subscription.plan=automator=new UiSelector().descriptionStartsWith("{customerSubscriptionName}")

#Customer Profile Account Header
mobile.customer.account.heading=accessibility=Profile Details
mobile.customer.edit_account.heading=accessibility=Edit Profile
mobile.customer.Landing_page.search_bar=accessibility=Find Services

#Customer Profile
mobile.customer.profile_icon.home_page=//android.view.View[contains(@content-desc, 'Profile Tab')]
mobile.customer.profile.edit=//android.widget.ImageView[starts-with(@content-desc, 'Customer')]

#Driver Logout Side
mobile.customer.manage_account.btn=accessibility=Manage Account
mobile.customer.logout.btn=accessibility=Logout
mobile.customer.logout.popup_btn=accessibility=Logout

#Ride Complete Heading
mobile.customer.ride_complete.heading=accessibility=Detail

#Customer Account Delete Section
mobile.customer.delete.btn=accessibility=Delete Account
mobile.customer.delete_sure.btn=accessibility=Delete

#mobile language section

mobile.customer.menu.Language.save_changes.btn=accessibility=Save Changes
mobile.customer.Language_menu.Tamil.btn=//android.view.View[@class='android.view.View' and @index='8']
mobile.customer.Language_menu.Hindi.btn=//android.view.View[@class='android.view.View' and @index='8']
mobile.customer.menu.Language_Tamil.save_changes.btn=(//android.widget.Button)[last()]
mobile.customer.menu.Language_Hindi.save_changes.btn=(//android.widget.Button)[last()]
mobile.customer.Language.btn=automator=new UiSelector().resourceId("account_item_languages")
mobile.customer.Language.Tamil.button=//android.widget.Button[@index='1']
mobile.customer.Language.Tamil.update.btn=//android.widget.ScrollView//android.view.View[@index='7']
mobile.customer.Language.Hindi.button=//android.widget.Button[@index='2']
mobile.customer.Language.English.button=accessibility=English

#Customer Wallet Module
mobile.customer.wallet.btn=accessibility=Wallet
mobile.customer.top_up.btn=accessibility=TopUp
mobile.customer.top_up_amount.hundred=accessibility=\u20B9 100.00
mobile.customer.top_up.proceed=accessibility=Proceed
mobile.customer.top_up.contact_no_box=automator=new UiSelector().className("android.widget.EditText")
mobile.customer.top_up.payment_option=automator=new UiSelector().text("Payment Options")
mobile.customer.top_up.net_banking=automator=new UiSelector().text("Netbanking")
mobile.customer.top_up.succes_popup=automator=new UiSelector().text("Success")

#Customer Registration From Mobile Side
mobile.customer.register_customer.name=automator=new UiSelector().className("android.widget.EditText").instance(0)
mobile.customer.register_customer.email=automator=new UiSelector().className("android.widget.EditText").instance(1)
mobile.customer.register_customer.gender.male=accessibility=Male
mobile.customer.register_customer.gender.female=accessibility=Female
mobile.customer.register_customer.checkbox=automator=new UiSelector().className("android.widget.CheckBox")
mobile.customer.register_customer.Terms_condition=automator=new UiSelector().description(" Terms & condition of use")
mobile.customer.register_customer.sign_up=accessibility=Sign Up
mobile.customer.register_customer.Profile=automator=new UiSelector().description("Profile Tab 5 of 5")

#Customer Emergency Number Section
mobile.customer.menu.Emergency=accessibility=Emergency Contact
mobile.customer.menu.Emergency.Emergency_Add_Number=accessibility=Add Emergency Contact Number
mobile.customer.menu.Emergency.Emergency_Number_Field=automator=new UiSelector().resourceId("register_emergency")
mobile.customer.menu.profile_edit.update=accessibility=Update
mobile.customer.menu.emergency.Emergency_call=accessibility=Emergency Call