# ==============================================================================
# ? WEB PLATFORM CONSOLE: GLOBAL DATA LOADER
# ==============================================================================

# Core Navigation Menus (Shared Layout Template Headers)
web.global.menu.dashboard=//i[@class='fa-house-chimney fa-solid iconstyle']
web.global.menu.settings=//i[contains(@class,'fa-cog')]
web.global.dashboard.statistics_header=//div[contains(text(),'Date Wise Statistics')]

# Platform System Authentication Engine
web.global.login.email=//input[@placeholder='Enter your email']
web.global.login.password=//input[@placeholder='Enter your password']
web.global.login.submit_btn=//button[@type='submit']

# Global Recurring Action Controls
web.global.action.submit=//button[normalize-space()='Submit']
web.global.action.close=//button[normalize-space()='Close']

# Central SweetAlert / Dialog Modal Controllers
web.global.dialog.btn_confirm_yes=//button[normalize-space()='Yes']
web.global.dialog.textarea_reason=//textarea[@id='swal2-textarea']

# Centralized System Alert Components (Toast Notification Dynamic Catchers)
web.global.toast.success=//div[@aria-label='Added Successfully']
web.global.toast.updated=//div[@aria-label='Updated Successfully']
web.global.toast.info=//div[@aria-label='Info']

# Global Session Authentication & Navigation Controllers
web.global.action.logout_link=//i[@class='fa-right-from-bracket fa-solid iconstyle']
web.global.action.logout_confirm=//button[normalize-space()='Logout']
web.global.action.sidebar_toggle=//*[local-name()='svg' and @id='Layer_1']
web.global.action.sidebar_logout_btn=//h2[normalize-space()='Logout']