# ==============================================================================
# ? WEB PLATFORM CONSOLE: SUPER ADMIN SETTING MODULE LOCATORS
# ==============================================================================

# Module Entry & Root Sidebar Controls
admin.setting.sidebar.menu=//h2[@id='Setting']


# Panic Call Module
admin.setting.panic_call.sidebar_menu=//span[@id='Panic Call']
admin.setting.panic_call.add_btn=//button[normalize-space()='Add Panic Calls']
admin.setting.panic_call.name_input=//input[@id='Name:']
admin.setting.panic_call.tamil_name_input=//input[@id='Name (Tamil):']
admin.setting.panic_call.hindi_name_input=//input[@id=' Name (Hindi):']
admin.setting.panic_call.contact_number=//input[@id='Contact Number:']
admin.setting.panic_call.status_dropdown=//div[@id='Panic Call Status:']
admin.setting.panic_call.activate_status_dropdown=//li[@aria-label='Activate']
admin.setting.panic_call.deactivate_status_dropdown=//li[@aria-label='Deactivate']
admin.setting.panic_call.search_name=//input[@aria-label='Name Filter Input']
admin.setting.panic_call.edit_btn=//i[@class='bi bi-pencil-square cursor-pointer gridIcon Edit']
admin.setting.panic_call.delete_btn=//i[@class='bi bi-trash cursor-pointer gridIcon Delete']
admin.setting.panic_call.confirm_delete_btn=//button[normalize-space()='Yes, delete it!']

# site setting Module
admin.setting.site_setting.sidebar_menu=//span[@id='Site Settings']
admin.setting.site_setting.wallet_dropdown=//div[@id='Wallet']
admin.setting.site_setting.walletdropdown_option_on=//li[@aria-label='on']
admin.setting.site_setting.walletdropdown_option_off=//li[@aria-label='off']