# ==============================================================================
# ? WEB PLATFORM CONSOLE: SUPER ADMIN SETTING MODULE LOCATORS
# ==============================================================================

# Module Entry & Root Sidebar Controls
admin.setting.sidebar.menu=//h2[@id='Setting']


# Panic Call Module
admin.setting.panic_call.sidebar_menu=//span[@id='Panic Call']
admin.setting.panic_call.add_btn=//button[normalize-space()='Add Panic Calls']
admin.setting.panic_call.name_input=//input[@id='Name:']
admin.setting.panic_call.tamil_name_input=//input[@id='Name (Tamil):']
admin.setting.panic_call.hindi_name_input=//input[@id=' Name (Hindi):']
admin.setting.panic_call.contact_number=//input[@id='Contact Number:']
admin.setting.panic_call.status_dropdown=//div[@id='Panic Call Status:']
admin.setting.panic_call.activate_status_dropdown=//li[@aria-label='Activate']
admin.setting.panic_call.deactivate_status_dropdown=//li[@aria-label='Deactivate']
admin.setting.panic_call.search_name=//input[@aria-label='Name Filter Input']
admin.setting.panic_call.edit_btn=//i[@class='bi bi-pencil-square cursor-pointer gridIcon Edit']
admin.setting.panic_call.delete_btn=//i[@class='bi bi-trash cursor-pointer gridIcon Delete']
admin.setting.panic_call.confirm_delete_btn=//button[normalize-space()='Yes, delete it!']

# site setting Module
admin.setting.site_setting.sidebar_menu=//span[@id='Site Settings']
admin.setting.site_setting.wallet_dropdown=//div[@id='Wallet']
admin.setting.site_setting.walletdropdown_option_on=//li[@aria-label='on']
admin.setting.site_setting.walletdropdown_option_off=//li[@aria-label='off']

# Geo Fencing Module
admin.setting.geo_fencing.sidebar_menu=//span[@id='Geo Fencing']
admin.setting.geo_fencing.add_restricted_area_btn=//button[normalize-space()='Add Restrcited Area']
admin.setting.geo_fencing.area_name_input_field=//input[@id='Restricted Area Name']
admin.setting.geo_fencing.status_toggle_button=//label[contains(@class,'cursor-pointer')]
admin.setting.geo_fencing.form_submit_button=//button[normalize-space()='Submit']
admin.setting.geo_fencing.area_search_filter=//input[@aria-label='AREA Filter Input']
admin.setting.geo_fencing.edit_button=//i[@title='Edit']
admin.setting.geo_fencing.delete_button=//i[@title='Delete']
admin.setting.geo_fencing.confirm_delete_button=//button[normalize-space()='Yes, delete it!']
