# =========================================================================
# ADMIN REPORT ISSUE MODULE LOCATORS REPOSITORY
# =========================================================================

# Main Module Entry Dashboard Landing Points
admin.report_issue.side_bar.menu=//h2[@id='Report Issue']


# Main Module Report Issue FAQ Section
admin.report_issue.side_bar_sub_menu.faqs=//div[normalize-space()='FAQs']
admin.report_issue.faqs.add_faq_btn=//button[normalize-space()='Add FAQ']
admin.report_issue.faqs.add_faq_input_title=//input[@id='Tittle:']
admin.report_issue.faqs.add_faq_input_description=//textarea[@placeholder='Enter Description']
admin.report_issue.faqs.add_faq_submit_button=//button[normalize-space()='Submit']
admin.report_issue.faqs.search_faq_filter_input=//input[@aria-label="Name Filter Input"]
admin.report_issue.faqs.faq_deactivate_btn=//i[contains(@class,'bi-hand-thumbs-down-fill')]
admin.report_issue.faqs.faq_activate_btn=//i[contains(@class,'bi-hand-thumbs-up-fill')]
admin.report_issue.faqs.faq_edit_btn=//i[contains(@class,'bi-pencil-square')]
admin.report_issue.faqs.faq_delete_btn=//i[@class='bi bi-trash cursor-pointer gridIcon Delete']
admin.report_issue.faqs.faq_confirm_delete_btn=//button[normalize-space()='Yes, delete it!']

# Main Module Report Issue Customer Report Issue Section
admin.report_issue.side_bar_sub_menu.customer_report_issues=//span[@id='Customer Report Issues']
admin.report_issue.customer_report_issues.search_btn=//button[normalize-space()='Search']
admin.report_issue.customer_report_issues.clear_btn=//button[normalize-space()='Clear']
admin.report_issue.customer_report_issues.created_by_dropdown=//span[@aria-label='Select a created by']
admin.report_issue.customer_report_issues.created_by_dropdown_search_box=//input[@role='searchbox']
admin.report_issue.customer_report_issues.created_by_dropdown_first_name=//li[@id='Created By_0']
admin.report_issue.customer_report_issues.status_dropdown=//div[@id='Status']
admin.report_issue.customer_report_issues.status_dropdown_unresolved_option=//li[@aria-label='Unresolved']
admin.report_issue.customer_report_issues.status_dropdown_resolved_option=//li[@aria-label='Resolved']
admin.report_issue.customer_report_issues.ticket_id_filter_input=//input[@aria-label='Ticket ID Filter Input']
admin.report_issue.customer_report_issues.eye_icon=//i[contains(@class,'View')]
admin.report_issue.customer_report_issues.close_eye_icon=//span[@id='closespan']
admin.report_issue.customer_report_issues.chat_icon=//i[@title='Chat']
admin.report_issue.customer_report_issues.chat_box=//textarea[@placeholder='Type a message...']
admin.report_issue.customer_report_issues.chat_box_enter_btn=//textarea[@placeholder='Type a message...']/following-sibling::button[2]
admin.report_issue.customer_report_issues.close_chat_icon=//i[contains(@class,'bi-x-circle')]
admin.report_issue.customer_report_issues.resolve_thumbs_icon=//i[@title='Resolve']
admin.report_issue.customer_report_issues.resolve_confirm_yes=//button[normalize-space()='Yes']
admin.report_issue.customer_report_issues.created_by_filter_input=//input[@aria-label='Created By Filter Input']
admin.report_issue.customer_report_issues.status_filter_input=//input[@aria-label='Status Filter Input']


# Main Module Report Issue Driver Report Issue Section
admin.report_issue.side_bar_sub_menu.driver_report_issues=//span[@id='Driver Report Issues']
admin.report_issue.driver_report_issues.search_btn=//button[normalize-space()='Search']
admin.report_issue.driver_report_issues.clear_btn=//button[normalize-space()='Clear']
admin.report_issue.driver_report_issues.created_by_dropdown=//span[@aria-label='Select a created by']
admin.report_issue.driver_report_issues.created_by_dropdown_search_box=//input[@role='searchbox']
admin.report_issue.driver_report_issues.created_by_dropdown_first_name=//li[@id='Created By_0']
admin.report_issue.driver_report_issues.status_dropdown=//div[@id='Status']
admin.report_issue.driver_report_issues.status_dropdown_unresolved_option=//li[@aria-label='Unresolved']
admin.report_issue.driver_report_issues.status_dropdown_resolved_option=//li[@aria-label='Resolved']
admin.report_issue.driver_report_issues.ticket_id_filter_input=//input[@aria-label='Ticket ID Filter Input']
admin.report_issue.driver_report_issues.eye_icon=//i[contains(@class,'View')]
admin.report_issue.driver_report_issues.close_eye_icon=//span[@id='closespan']
admin.report_issue.driver_report_issues.chat_icon=//i[@title='Chat']
admin.report_issue.driver_report_issues.close_chat_icon=//i[contains(@class,'bi-x-circle')]
admin.report_issue.driver_report_issues.resolve_thumbs_icon=//i[@title='Resolved']
admin.report_issue.driver_report_issues.resolve_confirm_yes=//button[normalize-space()='Yes']

